baseURL = "shees-usman.github.io"
languageCode = "en-us"
title = "Shees Usman"
showSubheader = true
showServices = true
showRecentWorks = true
showDownload = true
showClients = true

footerEnableContact = true
footerEnableFollowme = true
footerEnableTextWidget = false
footerEnableFormWidget = false
